const questions = {
  question: [
    { id:'q1', prompt:'你下班以後常常做什麼？', hints:['做什麼','跟誰','在哪裡','為什麼'], frames:['我下班以後常常＿＿＿。','有時候我會跟＿＿＿一起＿＿＿。','因為＿＿＿，所以＿＿＿。'], checks:['我有回答下班後做什麼。','我說了一個以上的細節。','我有說原因或感覺。','我的聲音聽得清楚。'] },
    { id:'q2', prompt:'你每天怎麼去上班？為什麼？', hints:['交通方式','需要多久','為什麼方便'], frames:['我每天坐／騎＿＿＿去上班。','從＿＿＿到公司要＿＿＿分鐘。','因為＿＿＿，所以我覺得很方便。'], checks:['我有說怎麼去上班。','我有回答為什麼。','我說了時間或地點。','我的聲音聽得清楚。'] },
    { id:'q3', prompt:'你休假的時候喜歡去哪裡？', hints:['去哪裡','跟誰','做什麼','感覺'], frames:['我休假的時候喜歡去＿＿＿。','我常常跟＿＿＿一起去。','我們會＿＿＿，我覺得＿＿＿。'], checks:['我有說喜歡去哪裡。','我有說跟誰或做什麼。','我有說感覺或原因。','我的聲音聽得清楚。'] },
    { id:'q4', prompt:'你比較喜歡自己煮飯，還是在外面吃？為什麼？', hints:['選一個','吃什麼','原因','頻率'], frames:['我比較喜歡＿＿＿。','我常常吃＿＿＿。','因為＿＿＿，所以＿＿＿。'], checks:['我有清楚選一個答案。','我有說吃什麼或多久一次。','我有說原因。','我的聲音聽得清楚。'] },
    { id:'q5', prompt:'你最常用手機做什麼？', hints:['做什麼','什麼時候','跟誰','為什麼'], frames:['我最常用手機＿＿＿。','我通常在＿＿＿的時候使用。','因為＿＿＿，所以＿＿＿。'], checks:['我有說用手機做什麼。','我有說時間或對象。','我有說原因。','我的聲音聽得清楚。'] },
    { id:'q6', prompt:'你喜歡臺灣的哪一種食物？為什麼？', hints:['食物','在哪裡吃','味道','原因'], frames:['我喜歡臺灣的＿＿＿。','我常常在＿＿＿吃。','它的味道＿＿＿，所以＿＿＿。'], checks:['我有說一種食物。','我有說地點或味道。','我有說原因。','我的聲音聽得清楚。'] },
    { id:'q7', prompt:'天氣不好的時候，你會做什麼？', hints:['什麼天氣','做什麼','跟誰','感覺'], frames:['天氣＿＿＿的時候，我會＿＿＿。','有時候我跟＿＿＿一起＿＿＿。','我覺得＿＿＿。'], checks:['我有說是哪種天氣。','我有說會做什麼。','我有補充人物或感覺。','我的聲音聽得清楚。'] },
    { id:'q8', prompt:'你買東西的時候最重視什麼？', hints:['價格','品質','地點','原因'], frames:['我買東西的時候最重視＿＿＿。','我通常會先＿＿＿。','因為＿＿＿，所以＿＿＿。'], checks:['我有回答最重視什麼。','我有說購物習慣。','我有說原因。','我的聲音聽得清楚。'] },
    { id:'q9', prompt:'你平常怎麼學中文？', hints:['方法','時間','跟誰','困難'], frames:['我平常用＿＿＿學中文。','我每天／每週＿＿＿。','我覺得最難的是＿＿＿。'], checks:['我有說學中文的方法。','我有說時間或頻率。','我有說困難或感覺。','我的聲音聽得清楚。'] },
    { id:'q10', prompt:'如果朋友來臺灣，你會帶他去哪裡？', hints:['地點','交通','活動','原因'], frames:['我會帶朋友去＿＿＿。','我們可以坐＿＿＿去。','在那裡可以＿＿＿，因為＿＿＿。'], checks:['我有說一個地點。','我有說交通或活動。','我有說原因。','我的聲音聽得清楚。'] }
  ],
  experience: [
    { id:'e1', prompt:'請說一說你第一次來臺灣的經驗。', hints:['什麼時候','為什麼來','剛來時','後來','感覺'], frames:['我在＿＿＿來臺灣。','剛來的時候，我＿＿＿。','後來＿＿＿。','現在我覺得＿＿＿。'], checks:['我有說什麼時候或為什麼來臺灣。','我有說剛來時發生的事。','我有說後來的情況。','我有說自己的感覺。'] },
    { id:'e2', prompt:'請說一說一次別人幫助你的經驗。', hints:['什麼時候','遇到什麼問題','誰幫忙','怎麼幫','結果'], frames:['有一次，我＿＿＿。','那時候我遇到＿＿＿。','後來＿＿＿幫我＿＿＿。','最後＿＿＿，我覺得＿＿＿。'], checks:['我有說自己遇到什麼問題。','我有說誰幫助我。','我有說對方怎麼幫忙。','我有說結果或感覺。'] },
    { id:'e3', prompt:'請說一說一次去看醫生的經驗。', hints:['哪裡不舒服','去哪裡','醫生說什麼','後來','感覺'], frames:['有一天，我覺得＿＿＿。','所以我去＿＿＿看醫生。','醫生叫我＿＿＿。','後來＿＿＿。'], checks:['我有說哪裡不舒服。','我有說去什麼地方看醫生。','我有說醫生的建議。','我有說後來的結果。'] },
    { id:'e4', prompt:'請說一說一次讓你很開心的休假經驗。', hints:['什麼時候','跟誰','去哪裡','做什麼','為什麼開心'], frames:['＿＿＿的時候，我跟＿＿＿去＿＿＿。','我們先＿＿＿，後來＿＿＿。','因為＿＿＿，所以我很開心。'], checks:['我有說時間、人物或地點。','我有說做了什麼。','我有按照順序說。','我有說為什麼開心。'] },
    { id:'e5', prompt:'請說一說一次上班遲到的經驗。', hints:['什麼時候','為什麼遲到','怎麼處理','結果'], frames:['有一天，我要去＿＿＿。','因為＿＿＿，所以我遲到了。','後來我＿＿＿。','最後＿＿＿。'], checks:['我有說時間或地點。','我有說遲到原因。','我有說怎麼處理。','我有說結果。'] },
    { id:'e6', prompt:'請說一說一次和朋友一起吃飯的經驗。', hints:['什麼時候','在哪裡','吃什麼','聊什麼','感覺'], frames:['＿＿＿的時候，我跟＿＿＿一起吃飯。','我們在＿＿＿吃＿＿＿。','後來我們＿＿＿。','我覺得＿＿＿。'], checks:['我有說人物和時間。','我有說地點或食物。','我有說一件發生的事。','我有說感覺。'] },
    { id:'e7', prompt:'請說一說一次找不到路的經驗。', hints:['去哪裡','怎麼迷路','問誰','最後怎麼到'], frames:['有一次，我要去＿＿＿。','可是我＿＿＿。','後來我問＿＿＿。','最後我＿＿＿。'], checks:['我有說要去哪裡。','我有說遇到的問題。','我有說向誰求助。','我有說最後結果。'] },
    { id:'e8', prompt:'請說一說一次學會新技能的經驗。', hints:['學什麼','誰教你','怎麼練習','結果'], frames:['我以前不會＿＿＿。','後來＿＿＿教我。','我每天／每週＿＿＿。','現在我可以＿＿＿。'], checks:['我有說學什麼。','我有說誰教或如何學。','我有說練習過程。','我有說結果。'] },
    { id:'e9', prompt:'請說一說一次搬家的經驗。', hints:['從哪裡搬到哪裡','為什麼','誰幫忙','感覺'], frames:['＿＿＿的時候，我從＿＿＿搬到＿＿＿。','因為＿＿＿。','那天＿＿＿幫我。','搬完以後，我覺得＿＿＿。'], checks:['我有說搬家地點。','我有說原因。','我有說誰幫忙或做了什麼。','我有說感覺。'] },
    { id:'e10', prompt:'請說一說一次收到禮物的經驗。', hints:['什麼時候','誰送的','什麼禮物','為什麼','感覺'], frames:['＿＿＿的時候，＿＿＿送我＿＿＿。','他／她送我的原因是＿＿＿。','收到以後，我覺得＿＿＿。'], checks:['我有說時間和人物。','我有說是什麼禮物。','我有說原因。','我有說感覺。'] }
  ],
  sequence: [
    { id:'s1', prompt:'請看圖片，說一說發生了什麼事。', scenes:[['🏪','女生去超商'],['👛','結帳時找不到錢包'],['🙋','店員一起幫忙找'],['🛍️','在袋子裡找到錢包']], hints:['人物與地點','遇到的問題','誰來幫忙','最後的結果'], frames:['有一天，一位女生去＿＿＿。','她要＿＿＿的時候，發現＿＿＿。','後來＿＿＿。','最後＿＿＿。'], checks:['我有說人物和地點。','我有說她遇到的問題。','我有說店員做了什麼。','我有說最後的結果。'] },
    { id:'s2', prompt:'請看圖片，說一說發生了什麼事。', scenes:[['🚌','男生坐公車'],['📱','下車後發現手機不見了'],['🏃','回到公車站找'],['😊','司機把手機還給他']], hints:['一開始在哪裡','發現什麼問題','做了什麼','結果'], frames:['一開始，男生＿＿＿。','下車以後，他發現＿＿＿。','所以他＿＿＿。','最後＿＿＿。'], checks:['我有說一開始男生在哪裡。','我有說手機不見了。','我有說他回去找。','我有說司機把手機還給他。'] },
    { id:'s3', prompt:'請看圖片，說一說發生了什麼事。', scenes:[['🌧️','外面突然下雨'],['☂️','女生沒有帶雨傘'],['👭','朋友和她一起撐傘'],['🏠','兩人平安回家']], hints:['天氣','遇到什麼問題','誰幫忙','最後去哪裡'], frames:['有一天，外面突然＿＿＿。','女生沒有＿＿＿。','後來她的朋友＿＿＿。','最後她們＿＿＿。'], checks:['我有說天氣的變化。','我有說女生沒帶雨傘。','我有說朋友怎麼幫忙。','我有說最後的結果。'] },
    { id:'s4', prompt:'請看圖片，說一說發生了什麼事。', scenes:[['🍳','男生準備早餐'],['🔥','鍋子冒煙'],['🧯','他趕快關火'],['🥪','最後改吃三明治']], hints:['一開始','發生什麼問題','怎麼處理','結果'], frames:['早上，男生＿＿＿。','沒想到＿＿＿。','他趕快＿＿＿。','最後＿＿＿。'], checks:['我有說一開始做什麼。','我有說鍋子冒煙。','我有說怎麼處理。','我有說最後吃什麼。'] },
    { id:'s5', prompt:'請看圖片，說一說發生了什麼事。', scenes:[['🚲','女生騎腳踏車'],['🛞','車輪突然沒氣'],['📞','她打電話給朋友'],['🔧','朋友來幫忙修理']], hints:['人物','交通工具','問題','誰幫忙','結果'], frames:['有一天，女生騎＿＿＿。','突然，她發現＿＿＿。','所以她＿＿＿。','後來＿＿＿。'], checks:['我有說女生在騎車。','我有說車輪的問題。','我有說她打電話。','我有說朋友來幫忙。'] },
    { id:'s6', prompt:'請看圖片，說一說發生了什麼事。', scenes:[['📦','快遞送來包裹'],['🏠','家裡沒有人'],['📱','快遞打電話'],['🤝','鄰居幫忙收包裹']], hints:['誰','送什麼','遇到什麼問題','怎麼解決'], frames:['快遞要送＿＿＿。','可是＿＿＿。','後來他＿＿＿。','最後＿＿＿。'], checks:['我有說快遞送包裹。','我有說家裡沒人。','我有說快遞打電話。','我有說鄰居幫忙。'] },
    { id:'s7', prompt:'請看圖片，說一說發生了什麼事。', scenes:[['🐶','小狗跑出家門'],['🔍','主人到處找'],['🌳','路人在公園看到牠'],['😊','小狗回到主人身邊']], hints:['一開始','誰在找','在哪裡找到','結果'], frames:['有一天，小狗＿＿＿。','主人很著急，所以＿＿＿。','後來，有人在＿＿＿看到牠。','最後＿＿＿。'], checks:['我有說小狗跑出去。','我有說主人到處找。','我有說在哪裡找到。','我有說最後結果。'] },
    { id:'s8', prompt:'請看圖片，說一說發生了什麼事。', scenes:[['🛒','女生去市場買菜'],['💳','結帳時不能刷卡'],['🏧','她去附近領錢'],['🥬','最後買好菜回家']], hints:['地點','遇到的問題','怎麼解決','最後'], frames:['女生去＿＿＿買菜。','結帳的時候＿＿＿。','所以她去＿＿＿。','最後＿＿＿。'], checks:['我有說去市場買菜。','我有說不能刷卡。','我有說去領錢。','我有說最後結果。'] }
  ]
};

const modeInfo={question:['回答問題','30 秒｜說答案，也說原因'],experience:['經驗描述','準備 50 秒｜回答 1 分鐘'],sequence:['看圖說故事','準備 50 秒｜回答 1 分鐘']};
const app=document.querySelector('#app'),homeButton=document.querySelector('#homeButton'),accountArea=document.querySelector('#accountArea'),accountName=document.querySelector('#accountName'),logoutButton=document.querySelector('#logoutButton'),languageSelect=document.querySelector('#languageSelect');
let stream=null,mediaRecorder=null,chunks=[],urls=[],current=null,attempts=[],timerHandle=null,mockState=null;
let session=null,profile=null,completedIds=new Set(),language=localStorage.getItem('tocfl-language')||'zh';
const cfg=window.TOCFL_CONFIG||{};

const uiText={
 zh:{language:'語言',login:'考生登入',passport:'護照號碼',birth:'出生年月日',help:'請輸入護照上的西元生日，格式為 YYYYMMDD。',loginButton:'登入',logout:'登出',home:'回首頁',welcome:'歡迎來到',room:'口說練習室',loginLead:'請使用報名考試時填寫的資料登入。',privacy:'錄音只留在這台裝置，不會上傳。',next:'完成這題，進入下一題',retry:'根據建議，再說一次',feedback:'看練習建議',download:'下載錄音'},
 id:{language:'Bahasa',login:'Masuk peserta',passport:'Nomor paspor',birth:'Tanggal lahir',help:'Masukkan tanggal lahir sesuai paspor: YYYYMMDD.',loginButton:'Masuk',logout:'Keluar',home:'Beranda',welcome:'Selamat datang di',room:'Ruang latihan berbicara',loginLead:'Gunakan data yang Anda isi saat mendaftar ujian.',privacy:'Rekaman hanya tersimpan di perangkat ini dan tidak diunggah.',next:'Selesai, lanjut soal berikutnya',retry:'Coba sekali lagi',feedback:'Lihat saran latihan',download:'Unduh rekaman'},
 vi:{language:'Ngôn ngữ',login:'Đăng nhập thí sinh',passport:'Số hộ chiếu',birth:'Ngày sinh',help:'Nhập ngày sinh trên hộ chiếu theo dạng YYYYMMDD.',loginButton:'Đăng nhập',logout:'Đăng xuất',home:'Trang chủ',welcome:'Chào mừng đến',room:'Phòng luyện nói',loginLead:'Dùng thông tin đã điền khi đăng ký thi.',privacy:'Bản ghi chỉ lưu trên thiết bị này và không được tải lên.',next:'Hoàn thành và sang câu tiếp',retry:'Nói lại theo góp ý',feedback:'Xem gợi ý luyện tập',download:'Tải bản ghi'},
 th:{language:'ภาษา',login:'เข้าสู่ระบบผู้สอบ',passport:'หมายเลขหนังสือเดินทาง',birth:'วันเดือนปีเกิด',help:'กรอกวันเกิดตามหนังสือเดินทางในรูปแบบ YYYYMMDD',loginButton:'เข้าสู่ระบบ',logout:'ออกจากระบบ',home:'หน้าหลัก',welcome:'ยินดีต้อนรับสู่',room:'ห้องฝึกพูด',loginLead:'ใช้ข้อมูลที่กรอกตอนสมัครสอบ',privacy:'ไฟล์เสียงอยู่ในอุปกรณ์นี้เท่านั้นและจะไม่ถูกอัปโหลด',next:'เสร็จแล้ว ไปข้อถัดไป',retry:'ลองพูดอีกครั้ง',feedback:'ดูคำแนะนำ',download:'ดาวน์โหลดเสียง'},
 en:{language:'Language',login:'Candidate login',passport:'Passport number',birth:'Date of birth',help:'Enter the date of birth on your passport as YYYYMMDD.',loginButton:'Log in',logout:'Log out',home:'Home',welcome:'Welcome to the',room:'Speaking Practice Room',loginLead:'Use the information entered when registering for the test.',privacy:'Recordings stay on this device and are not uploaded.',next:'Finish and continue',retry:'Try again',feedback:'View practice tips',download:'Download recording'}
};
function applyLanguage(){const t=uiText[language]||uiText.zh;document.documentElement.lang=language==='zh'?'zh-Hant':language;languageSelect.value=language;document.querySelector('.language-label').textContent=t.language;homeButton.textContent=t.home;logoutButton.textContent=t.logout;const login=document.querySelector('#loginForm');if(login){login.querySelector('h2').textContent=t.login;const labels=login.querySelectorAll('label');labels[0].textContent=t.passport;labels[1].textContent=t.birth;login.querySelector('.field-help').textContent=t.help;login.querySelector('#loginButton').textContent=t.loginButton;const copy=document.querySelector('.login-copy');copy.querySelector('h1').innerHTML=`${t.welcome}<br><span>${t.room}</span>`;copy.querySelector('h1 + p').textContent=t.loginLead;copy.querySelector('.privacy-note').innerHTML=`<span>●</span> ${t.privacy}`;}const complete=document.querySelector('#completeButton');if(complete)complete.textContent=t.next;const retry=document.querySelector('#retryButton');if(retry)retry.textContent=t.retry;const feedback=document.querySelector('#getFeedback');if(feedback)feedback.textContent=t.feedback;const download=document.querySelector('#downloadButton');if(download)download.textContent=t.download;}
languageSelect.onchange=()=>{language=languageSelect.value;localStorage.setItem('tocfl-language',language);applyLanguage()};

function clone(id){return document.querySelector(id).content.cloneNode(true)}
function showHome(){if(!session){showLogin();return}cleanupStream();clearInterval(timerHandle);mockState=null;app.replaceChildren(clone('#homeTemplate'));homeButton.classList.add('hidden');accountArea.classList.remove('hidden');accountName.textContent=profile?.display_name||'考生';document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>b.dataset.mode==='mock'?showMockIntro():showList(b.dataset.mode));const count=profile?.practice_count||0;document.querySelector('#progressSummary').textContent=count?`你已完成 ${count} 次練習，繼續加油！`:'第一次也沒關係，選一種題型開始說。';document.querySelector('#statsStrip').innerHTML=`<div class="stat-box"><strong>${profile?.completed_questions||0}</strong><span>完成題數</span></div><div class="stat-box"><strong>${profile?.practice_count||0}</strong><span>練習次數</span></div><div class="stat-box"><strong>${profile?.mock_count||0}</strong><span>完整模考</span></div>`;applyLanguage();app.focus();}
function showList(mode){app.replaceChildren(clone('#listTemplate'));homeButton.classList.remove('hidden');const [title,desc]=modeInfo[mode],items=questions[mode],nextIndex=items.findIndex(q=>!completedIds.has(q.id)),index=nextIndex<0?items.length:nextIndex;document.querySelector('#listEyebrow').textContent='循序練習';document.querySelector('#listTitle').textContent=title;document.querySelector('#listDescription').textContent='完成目前這一題後，系統才會顯示下一題。';const list=document.querySelector('#questionList');if(index>=items.length){list.innerHTML=`<div class="completed-message"><strong>你已完成這個題型的 ${items.length} 題！</strong><br>可以回到首頁練習其他題型，之後也能重新開始複習。</div>`;}else{const q=items[index],p=document.createElement('p');p.className='question-progress';p.textContent=`目前進度：第 ${index+1} 題／共 ${items.length} 題`;list.append(p);const b=document.createElement('button');b.className='question-item';b.innerHTML=`<span class="question-index">${index+1}</span><span><strong>${q.prompt}</strong><small>${desc}</small></span><span class="arrow">→</span>`;b.onclick=()=>startPractice(mode,q,false);list.append(b)}applyLanguage();app.focus();}
function startPractice(mode,q,isMock){current={mode,q,isMock};attempts=[];app.replaceChildren(clone('#practiceTemplate'));homeButton.classList.toggle('hidden',isMock);document.querySelector('#typeBadge').textContent=isMock?`小模考 ${mockState.index+1}/4`:modeInfo[mode]?.[0]||'暖身題';const prep=mode==='question'||mode==='warmup'?0:50,answer=mode==='question'?30:mode==='warmup'?15:60;current.prep=prep;current.answer=answer;document.querySelector('#timingLabel').textContent=prep?`準備 ${prep} 秒｜回答 ${answer} 秒`:`回答 ${answer} 秒`;document.querySelector('#promptText').textContent=q.prompt;document.querySelector('#timer').textContent=format(answer);document.querySelector('#speakPrompt').onclick=()=>speak(q.prompt);if(q.scenes)renderScenes(q.scenes);if(isMock){document.querySelector('#supportPanel').classList.add('hidden');document.querySelector('#micHelp').textContent='小模考只能錄一次，錄音結束後會自動進到下一題。'}else{renderHints(q);document.querySelector('#toggleHints').onclick=()=>document.querySelector('#hints').classList.toggle('hidden')};document.querySelector('#recordButton').onclick=beginFlow;document.querySelector('#stopButton').onclick=stopRecording;document.querySelector('#getFeedback').onclick=showFeedback;document.querySelector('#retryButton').onclick=retry;document.querySelector('#completeButton').onclick=completeCurrent;document.querySelector('#downloadButton').onclick=downloadCurrent;applyLanguage();app.focus();}
function renderHints(q){const h=document.querySelector('#hints');h.innerHTML=`<div class="hint-chips">${q.hints.map(x=>`<span class="hint-chip">${x}</span>`).join('')}</div>${q.frames.map(x=>`<p class="sentence-frame">${x}</p>`).join('')}`}
function renderScenes(scenes){const el=document.querySelector('#sequenceVisual');el.classList.remove('hidden');el.innerHTML=scenes.map((x,i)=>`<div class="scene"><b>${i+1}</b><span>${x[0]}</span><small>${x[1]}</small></div>`).join('')}
function speak(text){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='zh-TW';u.rate=.85;speechSynthesis.speak(u)}
async function beginFlow(){try{if(!stream)stream=await navigator.mediaDevices.getUserMedia({audio:true});document.querySelector('#recordButton').disabled=true;document.querySelector('#micHelp').textContent='';if(current.prep){await countdown(current.prep,'準備時間｜想 3–5 個關鍵詞',false)}await countdown(3,'準備開始',false);startRecording()}catch(e){showMicError()}}
function countdown(seconds,status,recording){return new Promise(resolve=>{let n=seconds;setTimer(n,status);timerHandle=setInterval(()=>{n--;setTimer(n,status);if(n<=0){clearInterval(timerHandle);resolve()}},1000)})}
function setTimer(n,status){document.querySelector('#timer').textContent=format(n);document.querySelector('#timerStatus').textContent=status}
function format(n){return `00:${String(n).padStart(2,'0')}`}
function startRecording(){chunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};mediaRecorder.onstop=finishRecording;mediaRecorder.start();const btn=document.querySelector('#recordButton');btn.classList.add('recording');btn.querySelector('b').textContent='錄音中';document.querySelector('#stopButton').classList.remove('hidden');let n=current.answer;setTimer(n,'正在回答');timerHandle=setInterval(()=>{n--;setTimer(n,n<=10?'剩下最後幾秒':'正在回答');if(n<=0)stopRecording()},1000)}
function stopRecording(){clearInterval(timerHandle);if(mediaRecorder&&mediaRecorder.state==='recording')mediaRecorder.stop()}
async function finishRecording(){const blob=new Blob(chunks,{type:mediaRecorder.mimeType||'audio/webm'}),url=URL.createObjectURL(blob);urls.push(url);const duration=current.answer-parseInt(document.querySelector('#timer').textContent.split(':')[1]||0);attempts.push({blob,url,duration:Math.max(1,duration)});cleanupStream();await recordPractice(current.q.id);if(current.isMock){mockState.recordings.push({q:current.q,mode:current.mode,blob,url});setTimeout(nextMock,600);return}showReview()}
function showReview(){document.querySelector('#recorder').classList.add('hidden');const section=document.querySelector('#reviewSection');section.classList.remove('hidden');document.querySelector('#audioPlayer').src=attempts.at(-1).url;document.querySelector('#takeBadge').textContent=attempts.length===1?'第一次':'第二次';const list=document.querySelector('#checklist');list.innerHTML=current.q.checks.map((c,i)=>`<label class="check-item"><input type="checkbox" value="${i}"><span>${c}</span></label>`).join('');document.querySelector('#feedback').classList.add('hidden');document.querySelector('#getFeedback').classList.remove('hidden');document.querySelector('#retryButton').classList.add('hidden');document.querySelector('#completeButton').classList.add('hidden');applyLanguage();section.scrollIntoView({behavior:'smooth'});localStorage.setItem('tocfl-practice-count',Number(localStorage.getItem('tocfl-practice-count')||0)+1)}
function showFeedback(){const boxes=[...document.querySelectorAll('#checklist input')],yes=boxes.filter(x=>x.checked).length,missing=boxes.findIndex(x=>!x.checked);const fb=document.querySelector('#feedback');let message=yes===boxes.length?'你已經完成這一題的四個重點。第二次試著不看完整句子，只看關鍵詞回答。':`下一次先改善一件事：${current.q.checks[missing].replace('我有','請記得')}`;fb.innerHTML=`<strong>${yes>=3?'做得不錯！':'已經完成第一次，這就是進步的開始。'}</strong>${message}`;fb.classList.remove('hidden');document.querySelector('#getFeedback').classList.add('hidden');document.querySelector('#retryButton').classList.remove('hidden');document.querySelector('#completeButton').classList.remove('hidden');applyLanguage()}
function retry(){document.querySelector('#reviewSection').classList.add('hidden');document.querySelector('#recorder').classList.remove('hidden');document.querySelector('#recordButton').disabled=false;document.querySelector('#recordButton').classList.remove('recording');document.querySelector('#recordButton b').textContent='再說一次';document.querySelector('#timer').textContent=format(current.answer);document.querySelector('#timerStatus').textContent='只看關鍵詞，再說一次';if(attempts.length>=2){showComparison();return}document.querySelector('#recorder').scrollIntoView({behavior:'smooth'})}
function showComparison(){const c=document.querySelector('#comparison');c.classList.remove('hidden');c.innerHTML=`<h2>比較兩次回答</h2><p>聽聽看：第二次有沒有多一個細節？是不是更容易理解？</p><div class="take-grid">${attempts.slice(0,2).map((a,i)=>`<div class="take-card"><strong>${i?'第二次':'第一次'}｜約 ${a.duration} 秒</strong><audio src="${a.url}" controls></audio></div>`).join('')}</div><div class="action-row"><button class="primary-button" id="donePractice">${(uiText[language]||uiText.zh).next}</button></div>`;document.querySelector('#donePractice').onclick=completeCurrent}
function completeCurrent(){if(!current||current.isMock)return showHome();completedIds.add(current.q.id);const items=questions[current.mode],i=items.findIndex(q=>q.id===current.q.id);if(i>=0&&i+1<items.length)startPractice(current.mode,items[i+1],false);else showList(current.mode)}
function downloadCurrent(){const a=document.createElement('a');a.href=attempts.at(-1).url;a.download=`TOCFL-${current.q.id}-${attempts.length}.webm`;a.click()}
function showMicError(){const rec=document.querySelector('#recorder');let e=rec.querySelector('.error-message');if(!e){e=document.createElement('div');e.className='error-message';rec.append(e)}e.textContent='目前無法使用麥克風。請在瀏覽器設定中允許麥克風，並確認不是在無痕模式中開啟。';document.querySelector('#recordButton').disabled=false}
function cleanupStream(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
function showMockIntro(){app.replaceChildren(clone('#mockIntroTemplate'));homeButton.classList.remove('hidden');document.querySelector('#startMock').onclick=startMock;app.focus()}
function startMock(){const warm={id:'w1',prompt:'請說一說你叫什麼名字、來自哪裡。',checks:[]};mockState={index:0,recordings:[],items:[{mode:'warmup',q:warm},{mode:'question',q:questions.question[1]},{mode:'experience',q:questions.experience[1]},{mode:'sequence',q:questions.sequence[0]}]};const item=mockState.items[0];startPractice(item.mode,item.q,true)}
function nextMock(){mockState.index++;if(mockState.index>=mockState.items.length){showMockResults();return}const item=mockState.items[mockState.index];startPractice(item.mode,item.q,true)}
function showMockResults(){cleanupStream();app.replaceChildren(clone('#mockResultTemplate'));homeButton.classList.remove('hidden');const list=document.querySelector('#mockRecordings');mockState.recordings.forEach((r,i)=>{const d=document.createElement('div');d.className='mock-recording';d.innerHTML=`<strong>${i+1}. ${r.q.prompt}</strong><audio src="${r.url}" controls></audio>`;list.append(d)});document.querySelector('#finishMock').onclick=async()=>{await rpc('record_mock',{});await loadProfile();showHome()};app.focus()}

function showLogin(message=''){cleanupStream();session=null;profile=null;completedIds=new Set();homeButton.classList.add('hidden');accountArea.classList.add('hidden');app.replaceChildren(clone('#loginTemplate'));const form=document.querySelector('#loginForm'),err=document.querySelector('#loginError');if(message){err.textContent=message;err.classList.remove('hidden')}form.onsubmit=login;applyLanguage();app.focus();}
async function hashHex(value){const bytes=new TextEncoder().encode(value),digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function login(e){e.preventDefault();const button=document.querySelector('#loginButton'),err=document.querySelector('#loginError'),passport=document.querySelector('#passportInput').value.trim().toUpperCase().replace(/\s+/g,''),birth=document.querySelector('#birthInput').value.replace(/\D/g,'');err.classList.add('hidden');if(birth.length!==8){err.textContent='登入資料不正確，請確認護照號碼及出生年月日。';err.classList.remove('hidden');return}button.disabled=true;button.textContent='登入中…';try{const email=(await hashHex(passport))+'@tocfl.practice.invalid',res=await fetch(`${cfg.supabaseUrl}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:cfg.supabasePublishableKey,'Content-Type':'application/json'},body:JSON.stringify({email,password:birth})});if(!res.ok)throw new Error();session=await res.json();localStorage.setItem('tocfl-session',JSON.stringify(session));await loadProfile();if(!profile?.enabled){await logout();throw new Error()}const languageMap={'中文':'zh','印尼文':'id','越南文':'vi','泰文':'th','英文':'en'};if(languageMap[profile.interface_language]){language=languageMap[profile.interface_language];localStorage.setItem('tocfl-language',language)}await loadPracticeIds();await rpc('touch_login',{});showHome()}catch(_){showLogin('登入資料不正確，請確認護照號碼及出生年月日。')}finally{button.disabled=false}}
async function rest(path,options={}){if(!session)throw new Error('no session');return fetch(`${cfg.supabaseUrl}/rest/v1/${path}`,{...options,headers:{apikey:cfg.supabasePublishableKey,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json',...(options.headers||{})}})}
async function rpc(name,body){const r=await rest(`rpc/${name}`,{method:'POST',body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r}
async function loadProfile(){const r=await rest('profiles?select=display_name,interface_language,enabled,completed_questions,practice_count,mock_count&limit=1');if(!r.ok)throw new Error();profile=(await r.json())[0];return profile}
async function loadPracticeIds(){const r=await rest('practice_items?select=question_id');if(!r.ok)throw new Error();completedIds=new Set((await r.json()).map(x=>x.question_id));return completedIds}
async function recordPractice(id){try{await rpc('record_practice',{p_question_id:id});completedIds.add(id);await loadProfile()}catch(_){}}
async function restoreSession(){try{const saved=JSON.parse(localStorage.getItem('tocfl-session')||'null');if(!saved?.access_token)return showLogin();session=saved;await loadProfile();if(!profile?.enabled)throw new Error();await loadPracticeIds();showHome()}catch(_){localStorage.removeItem('tocfl-session');showLogin()}}
async function logout(){session=null;profile=null;localStorage.removeItem('tocfl-session');showLogin()}
homeButton.onclick=showHome;logoutButton.onclick=logout;window.addEventListener('beforeunload',()=>{cleanupStream();urls.forEach(URL.revokeObjectURL)});restoreSession();
